{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "query_result(count(pg_database_size_bytes) by (datname))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Использование shared_buffers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение подключений по состояниям",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент попаданий в кэш буферов",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit{datname=~\"${database:regex}\"}[5m])) by (datname) / \n(sum(rate(pg_stat_database_blks_hit{datname=~\"${database:regex}\"}[5m])) by (datname) + \nsum(rate(pg_stat_database_blks_read{datname=~\"${database:regex}\"}[5m])) by (datname)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Топ баз данных по активности",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(pg_stat_database_tup_fetched{datname=~\"${database:regex}\"}[5m]))\n",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Время выполнения запросов по базам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total{datname=~\"${database:regex}\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Количество пользователей и их лимиты",
   "type": "table",
   "description": "Показывает лимиты подключений для ролей",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "pg_roles_connection_limit", "legendFormat": "{{rolname}}" }
   ]
  },
  {
   "title": "Средняя длительность скрейпа",
   "type": "timeseries",
   "description": "Среднее время опроса PostgreSQL exporter за 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(pg_exporter_last_scrape_duration_seconds[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий объём всех баз (в гигабайтах)",
   "type": "stat",
   "description": "Суммарный размер всех баз данных",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{datname=~\"${database:regex}\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер базы данных (в гигабайтах)",
   "type": "bargauge",
   "description": "Размер каждой базы данных в ГБ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"${database:regex}\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Количество активных подключений",
   "type": "stat",
   "description": "Показывает количество активных соединений",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_locks_count{mode=\"accesssharelock\", datname=~\"$database\"}",
     "legendFormat": "{{datname}}"
    },
    {}
   ]
  }
 ]
}