{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "currency",
    "label": "Instance",
    "query": {
     "query": "query_result(count(custom_fx_rate) by (pair))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Валютный курс USD → EUR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_fx_rate{pair=~\"$currency\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Валютный курс EUR → KZT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_fx_rate{pair=\"EUR_KZT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Курс BTC/USD",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(custom_btc_price_usd[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя системная нагрузка",
   "type": "gauge",
   "description": "Средняя имитированная нагрузка за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(custom_sim_random_load[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость запросов в минуту",
   "type": "timeseries",
   "description": "Показывает изменение скорости запросов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(custom_sim_request_rate_per_min[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активные пользователи",
   "type": "gauge",
   "description": "Среднее число активных пользователей за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(custom_sim_active_users[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент успешных API-запросов",
   "type": "stat",
   "description": "Показывает стабильность работы API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(custom_api_success[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя скорость ветра",
   "type": "timeseries",
   "description": "Средняя скорость ветра за 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(custom_weather_windspeed_ms[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя влажность воздуха",
   "type": "stat",
   "description": "Средняя влажность за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(custom_weather_humidity_pct[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура за 5 минут (Astana)",
   "type": "timeseries",
   "description": "Показывает среднюю температуру за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(custom_weather_temperature_c[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}