{
 "title": "Node Exporter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(count(node_cpu_seconds_total) by (instance))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Входящий сетевой трафик в Мбит/сек",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Средняя нагрузка CPU за последнюю минуту",
   "type": "stat",
   "description": "Средняя нагрузка CPU за последнюю минуту",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"${instance:regex}\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость чтения с диска в MB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"${instance:regex}\"}[5m]) / 1024 / 1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Общая, доступная и используемая память в GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance:regex}\"} / 1024 / 1024 / 1024\n",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024\n",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Количество открытых файловых дескрипторов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_allocated{instance=~\"${instance:regex}\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент использования swap-памяти",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes{instance=~\"${instance:regex}\"} / node_memory_SwapTotal_bytes{instance=~\"${instance:regex}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время работы системы (аптайм) в часах",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds{instance=~\"${instance:regex}\"} - node_boot_time_seconds{instance=~\"${instance:regex}\"}) / 3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент используемой оперативной памяти",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=~\"${instance:regex}\"} / node_memory_MemTotal_bytes{instance=~\"${instance:regex}\"}))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент использования CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"${instance:regex}\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество активных процессов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_procs_running{instance=~\"${instance:regex}\"}) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}